name: Security Audit

# Checks for security vulnerabilities in dependencies
# - Runs on a weekly schedule (Sunday at midnight)
# - Runs when Cargo.toml or Cargo.lock files are modified
# - Uses cargo-audit to identify known vulnerabilities

on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly at midnight on Sunday
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  pull_request:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'

jobs:
  audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      
      - name: Install cargo-audit
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-audit
      
      - name: Run cargo-audit
        uses: actions-rs/cargo@v1
        with:
          command: audit
          args: --deny warnings
