name: Security Audit

# Checks for security vulnerabilities in dependencies
# - Runs on a weekly schedule (Sunday at midnight)
# - Runs when Cargo.toml or Cargo.lock files are modified
# - Uses cargo-audit to identify known vulnerabilities

on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly at midnight on Sunday
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  pull_request:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'

jobs:
  audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install stable toolchain
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      
      - name: Install cargo-audit
        uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505 # v1
        with:
          command: install
          args: cargo-audit
      
      - name: Run cargo-audit
        uses: actions-rs/cargo@v1
        with:
          command: audit
          args: --deny warnings
